# Generated by Django 5.0.1 on 2024-04-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['pk'], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
