# Generated by Django 5.0.1 on 2024-02-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_animelist_anime_alter_animelist_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimeList',
        ),
    ]
