# Generated by Django 5.0.1 on 2024-03-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
