# Generated by Django 5.0.1 on 2024-06-18 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffManga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='is available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('manga_id', models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.CASCADE, related_name='person_manga', to='mangas.manga')),
                ('person_id', models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.CASCADE, related_name='person_manga', to='persons.person')),
            ],
            options={
                'verbose_name': 'staff manga',
                'verbose_name_plural': 'staff mangas',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffmanga',
            constraint=models.UniqueConstraint(fields=('person_id', 'manga_id'), name='unique_staff_manga'),
        ),
    ]
