# Generated by Django 5.0.1 on 2024-04-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_author_options_alter_author_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['pk'], 'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
    ]
