# Generated by Django 5.0.1 on 2024-06-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_staffmanga_staffmanga_unique_staff_manga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffManga',
        ),
    ]
