# Generated by Django 5.0.1 on 2024-06-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alternate_names',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='alternative names'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(blank=True, help_text='last_name', max_length=255, verbose_name='family name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.CharField(blank=True, help_text='first_name', max_length=255, verbose_name='given name'),
        ),
    ]
