# Generated by Django 5.0.1 on 2024-04-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['pk'], 'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
