# Generated by Django 5.0.1 on 2024-06-05 18:49

import apps.utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_delete_new_news_title_idx_news_tag_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=apps.utils.paths.picture_image_path, verbose_name='image'),
        ),
    ]
