# Generated by Django 5.0.1 on 2024-07-02 19:20

import apps.utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=apps.utils.paths.image_path, verbose_name='image'),
        ),
    ]
