# Generated by Django 5.0.1 on 2024-06-05 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_animestats'),
        ('mangas', '0003_mangastats'),
        ('news', '0003_alter_news_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='title_idx',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
