# Generated by Django 5.0.1 on 2024-02-08 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('contents', '0002_remove_anime_rating_id_anime_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='season',
            name='name',
        ),
        migrations.RemoveField(
            model_name='season',
            name='slug',
        ),
        migrations.AddField(
            model_name='season',
            name='season',
            field=models.IntegerField(choices=[(0, 'Pendign'), (1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Fall')], default=0, verbose_name='Season'),
        ),
        migrations.AddField(
            model_name='season',
            name='year',
            field=models.IntegerField(default=2010, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Year'),
        ),
    ]
