# Generated by Django 5.0.1 on 2024-03-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_season_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fullname'),
        ),
    ]
