# Generated by Django 5.0.1 on 2024-02-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_delete_rating_remove_season_name_remove_season_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Fall')], default=0, verbose_name='Season'),
        ),
    ]
