# Generated by Django 5.0.1 on 2024-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_demographic_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('pending', 'Pending'), ('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], default='pending', max_length=10, verbose_name='season'),
        ),
    ]
