# Generated by Django 5.0.1 on 2024-02-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_season_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='season',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='url',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Available'),
        ),
    ]
