# Generated by Django 5.0.1 on 2024-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_season_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='fullname'),
        ),
    ]
