# Generated by Django 5.0.1 on 2024-03-07 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(db_index=True, default=2010, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name (ENG)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
