# Generated by Django 5.0.1 on 2024-02-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_author_available_alter_demographic_available_and_more'),
        ('contents', '0005_alter_manga_author_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
