# Generated by Django 5.0.1 on 2024-04-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_season_fullname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demographic',
            options={'ordering': ['pk'], 'verbose_name': 'demographic', 'verbose_name_plural': 'demographics'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['pk'], 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['pk'], 'verbose_name': 'season', 'verbose_name_plural': 'season'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['pk'], 'verbose_name': 'studio', 'verbose_name_plural': 'studios'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['pk'], 'verbose_name': 'theme', 'verbose_name_plural': 'themes'},
        ),
    ]
