# Generated by Django 5.0.1 on 2024-02-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_url_tag'),
        ('contents', '0008_remove_anime_url_id_remove_manga_url_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url',
        ),
    ]
