# Generated by Django 5.0.1 on 2024-02-07 21:43

import apps.utils.paths
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name (ENG)')),
                ('name_jpn', models.CharField(max_length=255, unique=True, verbose_name='Name (JPN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.paths.image_path, verbose_name='Image')),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='Synopsis')),
                ('episodes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1500)], verbose_name='Episodes')),
                ('duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Duration')),
                ('release', models.DateField(blank=True, null=True, verbose_name='Release')),
                ('category', models.CharField(choices=[('P', 'Pending'), ('O', 'ONA'), ('S', 'Series'), ('M', 'Movies')], default='P', max_length=1, verbose_name='Category')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Airing'), ('F', 'Finished'), ('U', 'Upcoming')], default='P', max_length=1, verbose_name='Status')),
                ('genre_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.genre')),
                ('rating_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.rating')),
                ('season_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.season')),
                ('studio_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.studio')),
                ('url_id', models.ManyToManyField(blank=True, to='categories.url')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name (ENG)')),
                ('name_jpn', models.CharField(max_length=255, unique=True, verbose_name='Name (JPN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.paths.image_path, verbose_name='Image')),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='Synopsis')),
                ('chapters', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chapters')),
                ('release', models.DateField(blank=True, null=True, verbose_name='Release')),
                ('category', models.CharField(choices=[('P', 'Pending'), ('O', 'Manga')], default='P', max_length=1, verbose_name='Category')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Airing'), ('F', 'Finished'), ('U', 'Upcoming')], default='P', max_length=1, verbose_name='Status')),
                ('author_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.author')),
                ('demographic_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.demographic')),
                ('genre_id', models.ManyToManyField(blank=True, to='categories.genre')),
                ('url_id', models.ManyToManyField(blank=True, to='categories.url')),
            ],
            options={
                'verbose_name': 'Manga',
                'verbose_name_plural': 'Mangas',
            },
        ),
    ]
