# Generated by Django 5.0.1 on 2024-03-26 15:53

import apps.utils.paths
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_demographic_options_alter_genre_options_and_more'),
        ('contents', '0001_initial'),
        ('persons', '0002_alter_author_options_alter_author_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'anime', 'verbose_name_plural': 'animes'},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name': 'manga', 'verbose_name_plural': 'mangas'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='category',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'TV'), (2, 'OVA'), (3, 'Movie'), (4, 'Special'), (5, 'ONA'), (6, 'Music')], default=0, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1500)], verbose_name='episodes'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.paths.image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='mean',
            field=models.FloatField(blank=True, null=True, verbose_name='mean'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='name (eng)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name_jpn',
            field=models.CharField(max_length=255, unique=True, verbose_name='name (jpn)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name_rom',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='name (rmj)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='num_list_users',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of list users'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='num_scoring_users',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of scoring users'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='popularity',
            field=models.IntegerField(blank=True, null=True, verbose_name='popularity'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'G - All Ages'), (2, 'PG - Children'), (3, 'PG-13 - Teens 13 and Older'), (4, 'R - 17+ (Violence & Profanity)'), (5, 'R+ - Profanity & Mild Nudity'), (6, 'RX - Hentai')], default=0, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release',
            field=models.DateField(blank=True, null=True, verbose_name='release'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Finished'), (2, 'Airing'), (3, 'Upcoming')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(blank=True, null=True, verbose_name='synopsis'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='chapters',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='chapters'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='demographic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.demographic', verbose_name='demographic'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(blank=True, to='categories.genre', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.paths.image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='mean',
            field=models.FloatField(blank=True, null=True, verbose_name='mean'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='media_type',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Manga'), (2, 'Novel'), (3, 'One Shot'), (4, 'Doujinshi'), (5, 'Manhwa'), (6, 'OEL')], default=0, verbose_name='media type'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='name (eng)'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='name_jpn',
            field=models.CharField(max_length=255, unique=True, verbose_name='name (jpn)'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='name_rom',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='name (rmj)'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='num_list_users',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of list users'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='num_scoring_users',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of scoring users'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='popularity',
            field=models.IntegerField(blank=True, null=True, verbose_name='popularity'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='release',
            field=models.DateField(blank=True, null=True, verbose_name='release'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Finished'), (2, 'Airing'), (3, 'Upcoming')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='synopsis',
            field=models.TextField(blank=True, null=True, verbose_name='synopsis'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='themes',
            field=models.ManyToManyField(blank=True, to='categories.theme', verbose_name='themes'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='website',
            field=models.URLField(blank=True, max_length=255, verbose_name='website'),
        ),
    ]
