# Generated by Django 5.0.1 on 2024-02-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='urls/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='url',
            name='tag',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
