# Generated by Django 5.0.1 on 2024-03-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='genre_id',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='season_id',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='studio_id',
            new_name='studio',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='demographic_id',
            new_name='demographic',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='genre_id',
            new_name='genres',
        ),
    ]
