# Generated by Django 5.0.1 on 2024-02-08 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='rating_id',
        ),
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'G - All Ages'), (2, 'PG - Children'), (3, 'PG-13 - Teens 13 and Older'), (4, 'R - 17+ (Violence & Profanity)'), (5, 'R+ - Profanity & Mild Nudity'), (6, 'RX - Hentai')], default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='category',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'ONA'), (2, 'Series'), (3, 'Movies')], default=0, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1500)], verbose_name='Episodes'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Finished'), (2, 'Airing'), (3, 'Upcoming')], default=0, verbose_name='Status'),
        ),
    ]
