# Generated by Django 5.0.1 on 2024-02-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_url_image_alter_url_tag_alter_url_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='image',
        ),
        migrations.AlterField(
            model_name='url',
            name='tag',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Official Site'), ('C', 'Crunchyroll'), ('N', 'Netflix'), ('Y', 'Youtube Acccount'), ('X', 'X Account')], default='P', max_length=1, verbose_name='Tag'),
        ),
    ]
