# Generated by Django 5.0.1 on 2024-04-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_anime_options_alter_manga_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='category',
            field=models.CharField(choices=[('pending', 'Pending'), ('tv', 'TV'), ('ova', 'OVA'), ('movie', 'Movie'), ('special', 'Special'), ('ona', 'ONA'), ('music', 'Music')], default='pending', max_length=10, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(choices=[('pending', 'Pending'), ('g', 'G - All Ages'), ('pg', 'PG - Children'), ('pg13', 'PG-13 - Teens 13 and Older'), ('r', 'R - 17+ (Violence & Profanity)'), ('rplus', 'R+ - Profanity & Mild Nudity'), ('rx', 'RX - Hentai')], default='pending', max_length=10, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished'), ('airing', 'Airing'), ('upcoming', 'Upcoming')], default='pending', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='media_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('manga', 'Manga'), ('novel', 'Novel'), ('oneshot', 'One Shot'), ('doujinshi', 'Doujinshi'), ('manhwa', 'Manhwa'), ('oel', 'OEL')], default='pending', max_length=10, verbose_name='media type'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished'), ('airing', 'Airing'), ('upcoming', 'Upcoming')], default='pending', max_length=10, verbose_name='status'),
        ),
    ]
