# Generated by Django 5.0.1 on 2024-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_theme'),
        ('contents', '0002_rename_genre_id_anime_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='themes',
            field=models.ManyToManyField(blank=True, to='categories.theme'),
        ),
        migrations.AddField(
            model_name='manga',
            name='themes',
            field=models.ManyToManyField(blank=True, to='categories.theme'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='media_type',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Manga'), (2, 'Novel'), (3, 'One Shot'), (4, 'Doujinshi'), (5, 'Manhwa'), (6, 'OEL')], default=0, verbose_name='Media Type'),
        ),
    ]
