# Generated by Django 5.0.1 on 2024-03-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_anime_themes_manga_themes_alter_manga_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='name_rom',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Name (Romaji)'),
        ),
        migrations.AddField(
            model_name='manga',
            name='name_rom',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Name (Romaji)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name_jpn',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name (Japanese)'),
        ),
    ]
