# Generated by Django 5.0.1 on 2024-02-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_anime_available_alter_manga_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='category',
        ),
        migrations.AddField(
            model_name='manga',
            name='media_type',
            field=models.IntegerField(choices=[('0', 'Pending'), ('1', 'Manga'), ('2', 'Novel'), ('3', 'One Shot'), ('4', 'Doujinshi'), ('5', 'Manhwa'), ('6', 'OEL')], default=0, verbose_name='Media Type'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='category',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'TV'), (2, 'OVA'), (3, 'Movie'), (4, 'Special'), (5, 'ONA'), (6, 'Music')], default=0, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Finished'), (2, 'Airing'), (3, 'Upcoming')], default=0, verbose_name='Status'),
        ),
    ]
