# Generated by Django 5.0.1 on 2024-02-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_remove_url_image_alter_url_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Premiered',
            new_name='Season',
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Season'},
        ),
        migrations.RenameField(
            model_name='content',
            old_name='premiered_id',
            new_name='season_id',
        ),
    ]
