# Generated by Django 5.0.1 on 2024-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_rename_premiered_season_alter_season_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='url_id',
        ),
        migrations.AddField(
            model_name='content',
            name='url_id',
            field=models.ManyToManyField(to='contents.url'),
        ),
    ]
