# Generated by Django 5.0.1 on 2024-02-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_remove_manga_category_manga_media_type_and_more'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.author'),
        ),
    ]
