# Generated by Django 5.0.1 on 2024-04-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_anime_num_scoring_users_anime_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='num_scoring_users',
        ),
        migrations.AddField(
            model_name='manga',
            name='favorites',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='favorites'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='num_list_users',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='number of list users'),
        ),
    ]
