# Generated by Django 5.0.1 on 2024-02-04 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_content_url_id_content_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='episodes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1500)], verbose_name='Episodes'),
        ),
    ]
