# Generated by Django 5.0.1 on 2024-03-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_anime_synopsis_de_anime_synopsis_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='synopsis_de',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='synopsis_fr',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='synopsis_it',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='synopsis_pt',
        ),
    ]
