# Generated by Django 5.0.1 on 2024-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_remove_anime_synopsis_de_remove_anime_synopsis_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name (ENG)'),
        ),
    ]
