# Generated by Django 5.0.1 on 2024-02-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_url_tag'),
        ('contents', '0006_anime_mean_anime_num_list_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre_id',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre_id',
            field=models.ManyToManyField(blank=True, to='categories.genre'),
        ),
    ]
