# Generated by Django 5.0.1 on 2024-04-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_remove_manga_num_scoring_users_manga_favorites_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['pk'], 'verbose_name': 'anime', 'verbose_name_plural': 'animes'},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['pk'], 'verbose_name': 'manga', 'verbose_name_plural': 'mangas'},
        ),
    ]
