# Generated by Django 5.0.1 on 2024-03-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_alter_anime_name_alter_manga_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='synopsis_en',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='synopsis_es',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='synopsis_ja',
        ),
    ]
