# Generated by Django 5.0.1 on 2024-02-05 21:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_anime_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Demographic',
                'verbose_name_plural': 'Demographics',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name (ENG)')),
                ('name_jpn', models.CharField(max_length=255, unique=True, verbose_name='Name (JPN)')),
                ('image', models.ImageField(upload_to='contents/mangas/', verbose_name='Image')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('chapters', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Episodes')),
                ('release', models.DateField(verbose_name='Release')),
                ('category', models.CharField(choices=[('P', 'Pending'), ('O', 'Manga')], default='P', max_length=1, verbose_name='Category')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Airing'), ('F', 'Finished'), ('U', 'Upcoming')], default='P', max_length=1, verbose_name='Status')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.author')),
                ('demographic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.demographic')),
                ('genre_id', models.ManyToManyField(to='contents.genre')),
                ('url_id', models.ManyToManyField(to='contents.url')),
            ],
            options={
                'verbose_name': 'Manga',
                'verbose_name_plural': 'Mangas',
            },
        ),
    ]
