# Generated by Django 5.0.1 on 2024-02-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_remove_anime_genre_id_anime_genre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='url_id',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='url_id',
        ),
        migrations.AddField(
            model_name='anime',
            name='trailer',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='anime',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manga',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
