# Generated by Django 5.0.1 on 2024-02-06 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_author_demographic_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contents/animes/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.rating'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release',
            field=models.DateField(blank=True, null=True, verbose_name='Release'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.season'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.studio'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(blank=True, null=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='chapters',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chapters'),
        ),
    ]
