# Generated by Django 5.0.1 on 2024-02-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_alter_anime_image_alter_anime_url_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
