# Generated by Django 5.0.1 on 2024-06-08 03:52

import apps.utils.functions
import apps.utils.paths
import apps.utils.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='is available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.UUIDField()),
                ('name', models.CharField(default=apps.utils.functions.generate_random_code, max_length=100, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.paths.picture_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp']), apps.utils.validators.ImageSizeValidator(max_height=3000, max_width=3000), apps.utils.validators.FileSizeValidator(limit_mb=1)], verbose_name='image')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['anime', 'manga', 'character', 'person']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='is available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.UUIDField()),
                ('video', models.URLField(verbose_name='video')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['anime', 'manga']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['pk'],
            },
        ),
    ]
