# Generated by Django 5.0.1 on 2024-06-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='picture',
            index=models.Index(fields=['content_type', 'object_id'], name='utils_pictu_content_141a70_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['content_type', 'object_id'], name='utils_video_content_3ec751_idx'),
        ),
    ]
