# Generated by Django 5.0.1 on 2024-06-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['anime', 'manga']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
