# Generated by Django 5.0.1 on 2024-06-03 15:58

import apps.utils.functions
import apps.utils.paths
import apps.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('utils', '0002_alter_video_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default=apps.utils.functions.generate_random_code, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['anime', 'manga', 'character', 'person']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.paths.picture_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp']), apps.utils.validators.ImageSizeValidator(max_height=3000, max_width=3000), apps.utils.validators.FileSizeValidator(limit_mb=1)], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(verbose_name='video'),
        ),
    ]
