# Generated by Django 5.0.1 on 2024-05-31 18:41

import apps.utils.paths
import apps.utils.validators
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(db_index=True, default=True, verbose_name='available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name (eng)')),
                ('name_jpn', models.CharField(max_length=255, unique=True, verbose_name='name (jpn)')),
                ('established', models.CharField(blank=True, max_length=255, null=True, verbose_name='established')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.paths.image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webp']), apps.utils.validators.ImageSizeValidator(max_height=1080, max_width=1080), apps.utils.validators.FileSizeValidator(limit_mb=1)], verbose_name='image')),
            ],
            options={
                'verbose_name': 'studio',
                'verbose_name_plural': 'studios',
                'ordering': ['pk'],
            },
        ),
    ]
