# Generated by Django 5.0.1 on 2024-05-31 22:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(db_index=True, default=True, verbose_name='available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('season', models.CharField(choices=[('pending', 'Pending'), ('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], default='pending', max_length=10, verbose_name='season')),
                ('year', models.IntegerField(db_index=True, default=2010, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='year')),
                ('fullname', models.CharField(blank=True, max_length=255, unique=True, verbose_name='fullname')),
            ],
            options={
                'verbose_name': 'season',
                'verbose_name_plural': 'season',
                'ordering': ['pk'],
            },
        ),
    ]
