# Generated by Django 5.0.1 on 2024-05-31 18:41

import apps.utils.paths
import apps.utils.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(db_index=True, default=True, verbose_name='available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_kanji', models.CharField(max_length=255, verbose_name='name kanji')),
                ('favorites', models.PositiveIntegerField(default=0, verbose_name='favorites')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('role', models.CharField(choices=[('main', 'Main'), ('supporting', 'Supporting')], max_length=15, verbose_name='role')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.paths.image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webp']), apps.utils.validators.ImageSizeValidator(max_height=600, max_width=600), apps.utils.validators.FileSizeValidator(limit_mb=1)], verbose_name='image')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CharacterVoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(db_index=True, default=True, verbose_name='available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('language', models.CharField(choices=[('japanese', 'Japanese'), ('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('italian', 'Italian'), ('portuguese', 'Portuguese')], max_length=20, verbose_name='language')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character', verbose_name='character')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.person', verbose_name='voice')),
            ],
            options={
                'verbose_name': 'character voice',
                'verbose_name_plural': 'character voices',
                'ordering': ['pk'],
            },
        ),
    ]
