# Generated by Django 5.0.1 on 2024-06-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='characteranime',
            constraint=models.UniqueConstraint(fields=('character_id', 'anime_id'), name='unique_character_anime'),
        ),
    ]
