# Generated by Django 5.0.1 on 2024-06-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='charactervoice',
            constraint=models.UniqueConstraint(fields=('character_id', 'voice_id'), name='unique_character_voices'),
        ),
    ]
