# Generated by Django 5.0.1 on 2024-06-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_alter_anime_duration'),
        ('characters', '0002_charactervoice_unique_character_voices'),
        ('mangas', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='animes',
            field=models.ManyToManyField(blank=True, through='characters.CharacterAnime', to='animes.anime'),
        ),
        migrations.AddField(
            model_name='character',
            name='mangas',
            field=models.ManyToManyField(blank=True, through='characters.CharacterManga', to='mangas.manga'),
        ),
        migrations.AddField(
            model_name='character',
            name='voices',
            field=models.ManyToManyField(blank=True, through='characters.CharacterVoice', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='charactervoice',
            name='voice_id',
            field=models.ForeignKey(limit_choices_to={'category': 'voice_actor', 'is_available': True}, on_delete=django.db.models.deletion.CASCADE, related_name='character_voice', to='persons.person'),
        ),
    ]
