# Generated by Django 5.0.1 on 2024-06-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_characteranime_unique_character_anime'),
        ('mangas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='charactermanga',
            constraint=models.UniqueConstraint(fields=('character_id', 'manga_id'), name='unique_character_manga'),
        ),
    ]
