# Generated by Django 5.0.1 on 2024-06-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_charactermanga_unique_character_manga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactervoice',
            name='language',
        ),
    ]
