# Generated by Django 5.0.1 on 2024-05-29 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(fields=('club', 'user'), name='unique_club_user'),
        ),
    ]
