# Generated by Django 5.0.1 on 2024-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='is recommended'),
        ),
    ]
