# Generated by Django 5.0.1 on 2024-06-05 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0002_manga_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(db_index=True, default=True, verbose_name='available')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('reading', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('on_hold', models.PositiveIntegerField(default=0)),
                ('dropped', models.PositiveIntegerField(default=0)),
                ('plan_to_read', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('manga_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='mangas.manga')),
            ],
            options={
                'verbose_name': 'manga stats',
                'verbose_name_plural': 'manga stats',
                'ordering': ['pk'],
            },
        ),
    ]
