# Generated by Django 5.0.1 on 2024-03-01 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Watching'), (2, 'Completed'), (3, 'On Hold'), (4, 'Dropped'), (5, 'Plan to Watch')], db_index=True, default=0, max_length=20, verbose_name='Status')),
                ('is_watched', models.BooleanField(db_index=True, default=False, verbose_name='Is Watched')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.anime', verbose_name='Anime')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AnimeWatchlist',
                'verbose_name_plural': 'AnimeWatchlists',
            },
        ),
        migrations.CreateModel(
            name='MangaWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Watching'), (2, 'Completed'), (3, 'On Hold'), (4, 'Dropped'), (5, 'Plan to Watch')], db_index=True, default=0, max_length=20, verbose_name='Status')),
                ('is_watched', models.BooleanField(db_index=True, default=False, verbose_name='Is Watched')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.manga', verbose_name='Manga')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'MangaWatchlist',
                'verbose_name_plural': 'MangaWatchlists',
            },
        ),
    ]
