# Generated by Django 5.0.1 on 2024-02-12 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0003_alter_anime_available_alter_manga_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Watching'), (2, 'Completed'), (3, 'On Hold'), (4, 'Dropped'), (5, 'Plan to Watch')], default=0, max_length=20)),
                ('is_watched', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.anime', verbose_name='Anime')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AnimeWatchlist',
                'verbose_name_plural': 'AnimeWatchlists',
            },
        ),
    ]
