# Generated by Django 5.0.1 on 2024-02-12 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_anime_available_alter_manga_available'),
        ('watchlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animewatchlist',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='animewatchlist',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='animewatchlist',
            name='is_watched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Watched'),
        ),
        migrations.AlterField(
            model_name='animewatchlist',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='animewatchlist',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='animewatchlist',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Watching'), (2, 'Completed'), (3, 'On Hold'), (4, 'Dropped'), (5, 'Plan to Watch')], db_index=True, default=0, max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='MangaWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Watching'), (2, 'Completed'), (3, 'On Hold'), (4, 'Dropped'), (5, 'Plan to Watch')], db_index=True, default=0, max_length=20, verbose_name='Status')),
                ('is_watched', models.BooleanField(db_index=True, default=False, verbose_name='Is Watched')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.manga', verbose_name='Manga')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'MangaWatchlist',
                'verbose_name_plural': 'MangaWatchlists',
            },
        ),
    ]
