# Generated by Django 5.0.1 on 2024-03-26 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_anime_options_alter_manga_options_and_more'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'playlist', 'verbose_name_plural': 'playlists'},
        ),
        migrations.AlterModelOptions(
            name='playlistanime',
            options={'verbose_name': 'playlist anime', 'verbose_name_plural': 'playlist animes'},
        ),
        migrations.AlterModelOptions(
            name='playlistmanga',
            options={'verbose_name': 'playlist manga', 'verbose_name_plural': 'playlist mangas'},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='playlistanime',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_animes', to='contents.anime', verbose_name='anime'),
        ),
        migrations.AlterField(
            model_name='playlistanime',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='playlistanime',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='playlistanime',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is favorite'),
        ),
        migrations.AlterField(
            model_name='playlistanime',
            name='is_watched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is watched'),
        ),
        migrations.AlterField(
            model_name='playlistanime',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist', verbose_name='playlist'),
        ),
        migrations.AlterField(
            model_name='playlistanime',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('watching', 'Watching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan_watch', 'Plan to Watch')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='playlistanime',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is favorite'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='is_watched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is watched'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_mangas', to='contents.manga', verbose_name='manga'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist', verbose_name='playlist'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('watching', 'Watching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan_watch', 'Plan to Watch')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='updated at'),
        ),
    ]
