# Generated by Django 5.0.1 on 2024-03-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistanime',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Favorite'),
        ),
        migrations.AlterField(
            model_name='playlistanime',
            name='is_watched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Watched'),
        ),
        migrations.AlterField(
            model_name='playlistanime',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('watching', 'Watching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan_watch', 'Plan to Watch')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Favorite'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='is_watched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Watched'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('watching', 'Watching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan_watch', 'Plan to Watch')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
