# Generated by Django 5.0.1 on 2024-03-12 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_animes_playlistanime_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'MangaWatchlist', 'verbose_name_plural': 'MangaWatchlists'},
        ),
        migrations.AlterModelOptions(
            name='playlistanime',
            options={'verbose_name': 'MangaWatchlist', 'verbose_name_plural': 'MangaWatchlists'},
        ),
        migrations.AlterModelOptions(
            name='playlistmanga',
            options={'verbose_name': 'MangaWatchlist', 'verbose_name_plural': 'MangaWatchlists'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistanime',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='playlistanime',
            name='is_watched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Watched'),
        ),
        migrations.AddField(
            model_name='playlistanime',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='playlistanime',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='playlistanime',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='playlistmanga',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='playlistmanga',
            name='is_watched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Watched'),
        ),
        migrations.AddField(
            model_name='playlistmanga',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='playlistmanga',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='playlistmanga',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('watching', 'Watching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan_watch', 'Plan to Watch')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='playlistmanga',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tags'),
        ),
    ]
