# Generated by Django 5.0.1 on 2024-03-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_anime_options_alter_manga_options_and_more'),
        ('playlists', '0002_alter_playlist_options_alter_playlistanime_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistanime',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_anime', to='contents.anime', verbose_name='anime'),
        ),
        migrations.AlterField(
            model_name='playlistmanga',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_manga', to='contents.manga', verbose_name='manga'),
        ),
    ]
