# Generated by Django 5.0.1 on 2024-06-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_alter_anime_duration'),
        ('playlists', '0002_alter_animelist_user_alter_mangalist_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='animelistitem',
            constraint=models.UniqueConstraint(fields=('animelist_id', 'anime_id'), name='unique_animelist_anime'),
        ),
    ]
