# Generated by Django 5.0.1 on 2024-04-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlistanime_anime_alter_playlistmanga_manga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['pk'], 'verbose_name': 'playlist', 'verbose_name_plural': 'playlists'},
        ),
        migrations.AlterModelOptions(
            name='playlistanime',
            options={'ordering': ['pk'], 'verbose_name': 'playlist anime', 'verbose_name_plural': 'playlist animes'},
        ),
        migrations.AlterModelOptions(
            name='playlistmanga',
            options={'ordering': ['pk'], 'verbose_name': 'playlist manga', 'verbose_name_plural': 'playlist mangas'},
        ),
    ]
