# Generated by Django 5.0.1 on 2024-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0001_initial'),
        ('playlists', '0003_animelistitem_unique_animelist_anime'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mangalistitem',
            constraint=models.UniqueConstraint(fields=('mangalist_id', 'manga_id'), name='unique_mangalist_manga'),
        ),
    ]
