# Generated by Django 5.0.1 on 2024-03-13 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_alter_anime_name_alter_manga_name'),
        ('playlists', '0003_alter_playlist_options_alter_playlistanime_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='animes',
        ),
        migrations.RemoveField(
            model_name='playlistmanga',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='playlistmanga',
            name='playlist',
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlists'},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
        migrations.AddField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('watching', 'Watching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan_watch', 'Plan to Watch')], db_index=True, default='pending', max_length=20)),
                ('is_watched', models.BooleanField(db_index=True, default=False)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.anime')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.manga')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
            ],
            options={
                'verbose_name': 'PlaylistAnime',
                'verbose_name_plural': 'PlaylistAnime',
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='anime_items',
            field=models.ManyToManyField(through='playlists.PlaylistItem', to='contents.anime'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='manga_items',
            field=models.ManyToManyField(through='playlists.PlaylistItem', to='contents.manga'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes', models.ManyToManyField(to='contents.anime')),
                ('manga', models.ManyToManyField(to='contents.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PlaylistAnime',
        ),
        migrations.DeleteModel(
            name='PlaylistManga',
        ),
    ]
