# Generated by Django 5.0.1 on 2024-06-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='duration',
            field=models.DurationField(blank=True, verbose_name='duration'),
        ),
    ]
