# Generated by Django 5.0.1 on 2024-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_alter_anime_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='is recommended'),
        ),
    ]
