# Generated by Django 5.0.1 on 2024-08-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_alter_anime_image'),
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='licensors_id',
            field=models.ForeignKey(blank=True, help_text='LICENSOR tag', limit_choices_to={'is_available': True, 'type': 'licensor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licensed_animes', to='producers.producer', verbose_name='licensors'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='producers',
            field=models.ManyToManyField(help_text='DISTRIBUTOR tag', limit_choices_to={'is_available': True, 'type': 'distributor'}, related_name='produced_animes', to='producers.producer', verbose_name='producers'),
        ),
    ]
